# Análise de Volume de Treinos

Projeto simples de análise de dados utilizando Python e Pandas para analisar o volume total de treinos ao longo do tempo.

In [1]:
import pandas as pd

In [2]:
planilha = pd.read_csv('planilha_de_treinos.csv')

In [3]:

pd.to_datetime(planilha['data'], dayfirst=True)
planilha.info()

<class 'pandas.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   data       78 non-null     str
 1   treino     78 non-null     str
 2   exercicio  78 non-null     str
 3   carga kg   78 non-null     int64
 4   reps       78 non-null     int64
 5   series     78 non-null     int64
dtypes: int64(3), str(3)
memory usage: 3.8 KB

In [4]:

planilha['volume'] = planilha['carga kg'] * planilha['reps'] * planilha['series']
planilha.head()

         data treino         exercicio  carga kg  reps  series  volume
0  02/03/2026     t1      supino barra        25    10       5    1250
1  02/03/2026     t1    remada sentado        40    10       5    2000
2  02/03/2026     t1  elevação lateral        15    10       4     600
3  02/03/2026     t1    biceps sentado        12    10       4     480
4  02/03/2026     t1          legpress       200    10       5   10000

In [5]:
volume_por_dia = planilha.groupby('data')['volume'].sum()
volume_por_dia

data
02/03/2026    17530
04/03/2026    27200
06/03/2026    17530
09/03/2026    19530
11/03/2026    15110
13/03/2026    19530
16/03/2026    15110
18/03/2026    19530
20/03/2026    15110
23/03/2026    20730
25/03/2026    15110
27/03/2026    20730
Name: volume, dtype: int64

In [6]:
volume_por_dia = planilha.groupby('data')['volume'].sum().reset_index()
planilha.pivot_table(
    values='volume',
    index='data',
    columns='treino',
    aggfunc='sum'
)

treino           t1       t2
data
02/03/2026  17530.0      NaN
04/03/2026      NaN  27200.0
06/03/2026  17530.0      NaN
09/03/2026  19530.0      NaN
11/03/2026      NaN  15110.0
13/03/2026  19530.0      NaN
16/03/2026      NaN  15110.0
18/03/2026  19530.0      NaN
20/03/2026      NaN  15110.0
23/03/2026  20730.0      NaN
25/03/2026      NaN  15110.0
27/03/2026  20730.0      NaN